// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_RcppCgo_RCPPEXPORTS_H_GEN_
#define RCPP_RcppCgo_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace RcppCgo {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("RcppCgo", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("RcppCgo", "_RcppCgo_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in RcppCgo");
            }
        }
    }

    inline Rcpp::CharacterVector hi(Rcpp::CharacterVector v) {
        typedef SEXP(*Ptr_hi)(SEXP);
        static Ptr_hi p_hi = NULL;
        if (p_hi == NULL) {
            validateSignature("Rcpp::CharacterVector(*hi)(Rcpp::CharacterVector)");
            p_hi = (Ptr_hi)R_GetCCallable("RcppCgo", "_RcppCgo_hi");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_hi(Shield<SEXP>(Rcpp::wrap(v)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::CharacterVector >(rcpp_result_gen);
    }

}

#endif // RCPP_RcppCgo_RCPPEXPORTS_H_GEN_
